# This is a basic workflow to help you get started with Actions

name: Build Game

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Create build directory
        run: mkdir -p ${{ github.workspace }}/build

      # Runs a single command using the runners shell
      - name: Export Windows build
        run: |
          ~/environment/godot \
          --headless \
          --path ${{ github.workspace}}/truth_lies_and_democracy \
          --export-release "Windows" ${{ github.workspace }}/build/game.exe

      - name: Embed .pck into .exe
        run: |
          cat ${{ github.workspace }}/build/game.pck >> ${{ github.workspace }}/build/game.exe

      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: ${{ github.workspace }}/build/game.exe
